kind: pipeline
name: docker

platform:
  runner: 10.11.92.33

workspace:
  path: /go/src/kubevirt.io/hostpath-provisioner

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

steps:
  - name: patch
    image: registry.cn-qingdao.aliyuncs.com/wod/golang:1.17.8-alpine
    commands:
      - git apply .beagle/v0.12-provisioner.patch

  - name: golang
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-go-arch:1.17.8-alpine
    settings:
      binary: hostpath-provisioner
      main: cmd/provisioner

  - name: docker-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry.cn-qingdao.aliyuncs.com/wod/busybox:1.34-amd64
      dockerfile: .beagle/dockerfile
      cwd: dist
      repo: wod/hostpath-provisioner
      version: 'v0.12.0'
      channel: amd64
      args: 'TARGETOS=linux,TARGETARCH=amd64'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry.cn-qingdao.aliyuncs.com/wod/busybox:1.34-arm64
      dockerfile: .beagle/dockerfile
      cwd: dist
      repo: wod/hostpath-provisioner
      version: 'v0.12.0'
      channel: arm64
      args: 'TARGETOS=linux,TARGETARCH=arm64'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry.cn-qingdao.aliyuncs.com/wod/busybox:1.34-ppc64le
      dockerfile: .beagle/dockerfile
      cwd: dist
      repo: wod/hostpath-provisioner
      version: 'v0.12.0'
      channel: ppc64le
      args: 'TARGETOS=linux,TARGETARCH=ppc64le'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-mips64le
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry.cn-qingdao.aliyuncs.com/wod/busybox:1.34-mips64le
      dockerfile: .beagle/dockerfile
      cwd: dist
      repo: wod/hostpath-provisioner
      version: 'v0.12.0'
      channel: mips64le
      args: 'TARGETOS=linux,TARGETARCH=mips64le'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-arch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/mips64le
      template: registry.cn-qingdao.aliyuncs.com/wod/hostpath-provisioner:v0.12.0-ARCH
      target: registry.cn-qingdao.aliyuncs.com/wod/hostpath-provisioner:v0.12.0
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: secret
name: REGISTRY_USER_ALIYUN
get:
  name: USERNAME
  path: devops-registry-aliyun

---
kind: secret
name: REGISTRY_PASSWORD_ALIYUN
get:
  name: PASSWORD
  path: devops-registry-aliyun
