kind: pipeline
name: docker

platform:
  runner: 10.11.92.33

workspace:
  base: /go
  path: src/kubevirt.io/hostpath-provisioner

volumes:
  - name: go
    host:
      path: /data/cache/golang/pkg
  - name: docker
    host:
      path: /var/run/docker.sock

steps:

  - name: patch
    image: registry.cn-qingdao.aliyuncs.com/wod/golang:1.15.6-buster
    commands:
      - git apply .beagle/0001-provisioner.patch

  - name: golang
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-go-arch:1.15.6-buster
    volumes:
      - name: go
        path: /go/pkg
    settings:
      binary: hostpath-provisioner
      main: cmd/provisioner

  - name: docker-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry.cn-qingdao.aliyuncs.com/wod/debian:buster-slim-amd64
      dockerfile: .beagle/dockerfile
      cwd: dist
      repo: wod/hostpath-provisioner
      version: "v0.8.0"
      channel: amd64
      args: 'TARGETOS=linux,TARGETARCH=amd64'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - golang

  - name: docker-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry.cn-qingdao.aliyuncs.com/wod/debian:buster-slim-arm64
      dockerfile: .beagle/dockerfile
      cwd: dist
      repo: wod/hostpath-provisioner
      version: "v0.8.0"
      channel: arm64
      args: 'TARGETOS=linux,TARGETARCH=arm64'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - golang

  - name: docker-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry.cn-qingdao.aliyuncs.com/wod/debian:buster-slim-ppc64le
      dockerfile: .beagle/dockerfile
      cwd: dist
      repo: wod/hostpath-provisioner
      version: "v0.8.0"
      channel: ppc64le
      args: 'TARGETOS=linux,TARGETARCH=ppc64le'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - golang

  - name: docker-arch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:v1.2.3
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      platforms: linux/amd64,linux/arm64,linux/ppc64le
      template: registry.cn-qingdao.aliyuncs.com/wod/hostpath-provisioner:v0.8.0-ARCH
      target: registry.cn-qingdao.aliyuncs.com/wod/hostpath-provisioner:v0.8.0
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - docker-amd64
      - docker-arm64
      - docker-ppc64le

---
kind: secret
name: REGISTRY_USER_ALIYUN
get:
  name: USERNAME
  path: devops-registry-aliyun

---
kind: secret
name: REGISTRY_PASSWORD_ALIYUN
get:
  name: PASSWORD
  path: devops-registry-aliyun
