ARG BASE=alpine:3

FROM $BASE

ARG AUTHOR=mengkzhaoyun@gmail.com
ARG VERSION=v0.12.0

LABEL maintainer=${AUTHOR} version=${VERSION}

ARG TARGETOS
ARG TARGETARCH

COPY ./hostpath-provisioner-$TARGETOS-$TARGETARCH /hostpath-provisioner

CMD [ "/hostpath-provisioner" ]

