ARG BASE

FROM $BASE

ARG AUTHOR
ARG VERSION

LABEL maintainer=${AUTHOR} version=${VERSION}

ARG TARGETOS
ARG TARGETARCH

COPY ./dist/hostpath-provisioner-$TARGETOS-$TARGETARCH /hostpath-provisioner

CMD [ "/hostpath-provisioner" ]

